package com.example.poe.api.common.config;

import com.example.poe.api.data.SupportGem;

import java.util.HashMap;
import java.util.Map;

public class SupportGemInit {
    Map<String, SupportGem> dataList = new HashMap();

    public SupportGemInit() {
        dataList.put("강화보조",new SupportGem("강화 보조 (1)","특출난,보조","Empower_Support"));
        dataList.put("출혈확률보조",new SupportGem("출혈 확률 보조 (1)","공격,물리,보조","Chance_to_Bleed_Support"));
        dataList.put("무자비보조",new SupportGem("무자비 보조 (1)","강타,보조,근접,공격,타격","Ruthless_Support"));
        dataList.put("선대의부름보조",new SupportGem("선대의 부름 보조 (4)","보조,근접,공격,타격","Ancestral_Call_Support"));
        dataList.put("화염피해추가보조",new SupportGem("화염 피해 추가 보조 (8)","화염,물리,보조","Added_Fire_Damage_Support"));
        dataList.put("대지분쇄자보조",new SupportGem("대지 분쇄자 보조 (8)","공격,근접,강타,효과범위,보조,토템","Earthbreaker_Support"));
        dataList.put("화염나무보조",new SupportGem("화염나무 보조 (8)","보조,토템,주문,효과범위,화염,투사체,발동","Flamewood_Support"));
        dataList.put("밀어내기보조",new SupportGem("밀어내기 보조 (8)","보조","Knockback_Support"));
        dataList.put("명중시생명력획득보조",new SupportGem("명중 시 생명력 획득 보조 (8)","공격,보조","Life_Gain_on_Hit_Support"));
        dataList.put("생명력전환보조",new SupportGem("생명력 전환 보조 (8)","보조,지속시간","Lifetap_Support"));
        dataList.put("힘줄절단보조",new SupportGem("힘줄 절단 보조 (8)","공격,물리,보조","Maim_Support"));
        dataList.put("근접범위피해보조",new SupportGem("근접 범위 피해 보조 (8)","보조,근접,공격,타격,효과범위","Melee_Splash_Support"));
        dataList.put("쇠뇌토템보조",new SupportGem("쇠뇌 토템 보조 (8)","활,투사체,보조,토템","Ballista_Totem_Support"));
        dataList.put("주문토템보조",new SupportGem("주문 토템 보조 (8)","보조,주문,토템","Spell_Totem_Support"));
        dataList.put("기절보조",new SupportGem("기절 보조 (8)","보조","Stun_Support"));
        dataList.put("유혈충동보조",new SupportGem("유혈 충동 보조 (18)","공격,물리,보조,근접","Bloodlust_Support"));
        dataList.put("냉기화염전환보조",new SupportGem("냉기 화염 전환 보조 (18)","냉기,화염,보조","Cold_to_Fire_Support"));
        dataList.put("잔혹보조",new SupportGem("잔혹 보조 (18)","보조,지속시간","Cruelty_Support"));
        dataList.put("기절시인내충전보조",new SupportGem("기절 시 인내 충전 보조 (18)","보조,근접,공격","Endurance_Charge_on_Melee_Stun_Support"));
        dataList.put("강철손아귀보조",new SupportGem("강철 손아귀 보조 (18)","투사체,물리,보조","Iron_Grip_Support"));
        dataList.put("강철의의지보조",new SupportGem("강철의 의지 보조 (18)","주문,보조","Iron_Will_Support"));
        dataList.put("최대생명력시피해보조",new SupportGem("최대 생명력 시 피해 보조 (18)","공격,보조","Damage_on_Full_Life_Support"));
        dataList.put("근접물리피해보조",new SupportGem("근접 물리 피해 보조 (18)","근접,물리,보조,공격","Melee_Physical_Damage_Support"));
        dataList.put("격노보조",new SupportGem("격노 보조 (18)","보조,근접,공격","Rage_Support"));
        dataList.put("충격파보조",new SupportGem("충격파 보조 (18)","보조,근접,공격,효과범위","Shockwave_Support"));
        dataList.put("일촉즉발보조",new SupportGem("일촉즉발 보조 (18)","공격,보조","Volatility_Support"));
        dataList.put("공격시원소피해보조",new SupportGem("공격 시 원소 피해 보조 (18)","공격,보조","Elemental_Damage_with_Attacks_Support"));
        dataList.put("오만보조",new SupportGem("오만 보조 (31)","오라,보조","Arrogance_Support"));
        dataList.put("피의갈증보조",new SupportGem("피의 갈증 보조 (31)","공격,물리,보조","Bloodthirst_Support"));
        dataList.put("제어된불길보조",new SupportGem("제어된 불길 보조 (31)","화염,보조,근접,공격","Controlled_Blaze_Support"));
        dataList.put("타락시키는비명보조",new SupportGem("타락시키는 비명 보조 (31)","효과범위,물리,보조,함성,지속시간","Corrupting_Cry_Support"));
        dataList.put("신성한축복보조",new SupportGem("신성한 축복 보조 (31)","보조,오라,지속시간,축복","Divine_Blessing_Support"));
        dataList.put("화염관통보조",new SupportGem("화염 관통 보조 (31)","화염,보조","Fire_Penetration_Support"));
        dataList.put("방어상승보조",new SupportGem("방어 상승 보조 (31)","공격,보조,근접","Fortify_Support"));
        dataList.put("관대함보조",new SupportGem("관대함 보조 (31)","보조,오라","Generosity_Support"));
        dataList.put("수호자의축복보조",new SupportGem("수호자의 축복 보조 (31)","보조,오라,축복,소환수","Guardian's_Blessing_Support"));
        dataList.put("화상피해보조",new SupportGem("화상 피해 보조 (31)","화염,보조","Burning_Damage_Support"));
        dataList.put("지속시간증가보조",new SupportGem("지속시간 증가 보조 (31)","보조,지속시간","Increased_Duration_Support"));
        dataList.put("생명력흡수보조",new SupportGem("생명력 흡수 보조 (31)","보조","Life_Leech_Support"));
        dataList.put("분쇄보조",new SupportGem("분쇄 보조 (31)","효과범위,보조,근접,공격","Pulverise_Support"));
        dataList.put("지속시간감소보조",new SupportGem("지속시간 감소 보조 (31)","보조,지속시간","Less_Duration_Support"));
        dataList.put("영감보조",new SupportGem("영감 보조 (31)","치명타,보조","Inspiration_Support"));
        dataList.put("긴급명령보조",new SupportGem("긴급 명령 보조 (31)","함성,보조","Urgent_Orders_Support"));
        dataList.put("참수보조",new SupportGem("참수 보조 (38)","보조,근접,공격,타격","Behead_Support"));
        dataList.put("포악함보조",new SupportGem("포악함 보조 (38)","물리,보조","Brutality_Support"));
        dataList.put("피격시시전보조",new SupportGem("피격 시 시전 보조 (38)","보조,주문,발동","Cast_when_Damage_Taken_Support"));
        dataList.put("근접처치시시전보조",new SupportGem("근접 처치 시 시전 보조 (38)","보조,근접,공격,주문,발동","Cast_on_Melee_Kill_Support"));
        dataList.put("영원한축복보조",new SupportGem("영원한 축복 보조 (38)","보조,오라,축복","Eternal_Blessing_Support"));
        dataList.put("전쟁의주먹보조",new SupportGem("전쟁의 주먹 보조 (38)","강타,공격,근접,효과범위,보조","Fist_of_War_Support"));
        dataList.put("다중토템보조",new SupportGem("다중 토템 보조 (38)","토템,보조","Multiple_Totems_Support"));
        dataList.put("연속타격보조",new SupportGem("연속타격 보조 (38)","공격,근접,보조","Multistrike_Support"));
        dataList.put("외상보조",new SupportGem("외상 보조 (38)","물리,보조,근접,공격,타격,지속시간","Trauma_Support"));
        dataList.put("각성한화염피해추가보조",new SupportGem("각성한 화염 피해 추가 보조 (72)","화염,물리,보조","Awakened_Added_Fire_Damage_Support"));
        dataList.put("각성한선대의부름보조",new SupportGem("각성한 선대의 부름 보조 (72)","보조,근접,공격,타격","Awakened_Ancestral_Call_Support"));
        dataList.put("각성한포악함보조",new SupportGem("각성한 포악함 보조 (72)","물리,보조","Awakened_Brutality_Support"));
        dataList.put("각성한화상피해보조",new SupportGem("각성한 화상 피해 보조 (72)","화염,보조","Awakened_Burning_Damage_Support"));
        dataList.put("각성한강화보조",new SupportGem("각성한 강화 보조 (72)","특출난,보조","Awakened_Empower_Support"));
        dataList.put("각성한화염관통보조",new SupportGem("각성한 화염 관통 보조 (72)","화염,보조","Awakened_Fire_Penetration_Support"));
        dataList.put("각성한관대함보조",new SupportGem("각성한 관대함 보조 (72)","보조,오라","Awakened_Generosity_Support"));
        dataList.put("각성한근접물리피해보조",new SupportGem("각성한 근접 물리 피해 보조 (72)","근접,물리,보조,공격","Awakened_Melee_Physical_Damage_Support"));
        dataList.put("각성한근접범위피해보조",new SupportGem("각성한 근접 범위 피해 보조 (72)","보조,근접,공격,타격,효과범위","Awakened_Melee_Splash_Support"));
        dataList.put("각성한연속타격보조",new SupportGem("각성한 연속타격 보조 (72)","공격,근접,보조","Awakened_Multistrike_Support"));
        dataList.put("각성한공격시원소피해보조",new SupportGem("각성한 공격 시 원소 피해 보조 (72)","공격,보조","Awakened_Elemental_Damage_with_Attacks_Support"));
        dataList.put("향상보조",new SupportGem("향상 보조 (1)","특출난,보조","Enhance_Support"));
        dataList.put("중독확률보조",new SupportGem("중독 확률 보조 (1)","카오스,보조","Chance_to_Poison_Support"));
        dataList.put("기세보조",new SupportGem("기세 보조 (1)","공격,보조,지속시간","Momentum_Support"));
        dataList.put("신기루궁수보조",new SupportGem("신기루 궁수 보조 (4)","활,공격,보조,지속시간","Mirage_Archer_Support"));
        dataList.put("사격공세보조",new SupportGem("사격 공세 보조 (4)","보조,투사체","Volley_Support"));
        dataList.put("관통보조",new SupportGem("관통 보조 (4)","보조,투사체","Pierce_Support"));
        dataList.put("재빠른조립보조",new SupportGem("재빠른 조립 보조 (4)","보조,덫,지뢰","Swift_Assembly_Support"));
        dataList.put("냉기피해추가보조",new SupportGem("냉기 피해 추가 보조 (8)","냉기,보조","Added_Cold_Damage_Support"));
        dataList.put("정확도추가보조",new SupportGem("정확도 추가 보조 (8)","공격,보조","Additional_Accuracy_Support"));
        dataList.put("화살산개보조",new SupportGem("화살 산개 보조 (8)","활,공격,보조,투사체","Arrow_Nova_Support"));
        dataList.put("실명보조",new SupportGem("실명 보조 (8)","보조","Blind_Support"));
        dataList.put("도망칠확률보조",new SupportGem("도망칠 확률 보조 (8)","보조","Chance_to_Flee_Support"));
        dataList.put("공격속도증가보조",new SupportGem("공격 속도 증가 보조 (8)","공격,보조","Faster_Attacks_Support"));
        dataList.put("하위다중투사체보조",new SupportGem("하위 다중 투사체 보조 (8)","보조,투사체","Lesser_Multiple_Projectiles_Support"));
        dataList.put("궤적지뢰보조",new SupportGem("궤적 지뢰 보조 (8)","활,공격,보조,투사체,지뢰","Locus_Mine_Support"));
        dataList.put("마나벼림화살보조",new SupportGem("마나벼림 화살 보조 (8)","활,보조,발동","Manaforged_Arrows_Support"));
        dataList.put("다중덫보조",new SupportGem("다중 덫 보조 (8)","보조,덫","Multiple_Traps_Support"));
        dataList.put("덫보조",new SupportGem("덫 보조 (8)","보조,덫","Trap_Support"));
        dataList.put("공허조작보조",new SupportGem("공허 조작 보조 (8)","카오스,보조","Void_Manipulation_Support"));
        dataList.put("막기확률감소보조",new SupportGem("막기 확률 감소 보조 (18)","보조,지속시간","Block_Chance_Reduction_Support"));
        dataList.put("근접전투보조",new SupportGem("근접 전투 보조 (18)","보조,근접,공격,지속시간","Close_Combat_Support"));
        dataList.put("마무리타격보조",new SupportGem("마무리 타격 보조 (18)","보조","Culling_Strike_Support"));
        dataList.put("치명적인상태이상보조",new SupportGem("치명적인 상태 이상 보조 (18)","보조","Deadly_Ailments_Support"));
        dataList.put("밤의칼날보조",new SupportGem("밤의 칼날 보조 (18)","공격,치명타,보조","Nightblade_Support"));
        dataList.put("포악한투사체보조",new SupportGem("포악한 투사체 보조 (18)","투사체,공격,물리,카오스,보조","Vicious_Projectiles_Support"));
        dataList.put("근접사격보조",new SupportGem("근접 사격 보조 (18)","투사체,공격,보조","Point_Blank_Support"));
        dataList.put("가학증보조",new SupportGem("가학증 보조 (18)","보조","Sadism_Support"));
        dataList.put("덫및지뢰피해보조",new SupportGem("덫 및 지뢰 피해 보조 (18)","보조,덫,지뢰","Trap_and_Mine_Damage_Support"));
        dataList.put("냉기관통보조",new SupportGem("냉기 관통 보조 (31)","냉기,보조","Cold_Penetration_Support"));
        dataList.put("체온저하보조",new SupportGem("체온저하 보조 (31)","냉기,보조","Hypothermia_Support"));
        dataList.put("투사체속도증가보조",new SupportGem("투사체 속도 증가 보조 (31)","보조,투사체","Faster_Projectiles_Support"));
        dataList.put("쇠뇌집중사격보조",new SupportGem("쇠뇌 집중 사격 보조 (31)","투사체,보조,토템","Focused_Ballista_Support"));
        dataList.put("갈래보조",new SupportGem("갈래 보조 (31)","보조,투사체","Fork_Support"));
        dataList.put("얼음쐐기보조",new SupportGem("얼음 쐐기 보조 (31)","냉기,보조","Ice_Bite_Support"));
        dataList.put("충전된덫보조",new SupportGem("충전된 덫 보조 (31)","치명타,보조,덫","Charged_Traps_Support"));
        dataList.put("꿰뚫기보조",new SupportGem("꿰뚫기 보조 (31)","공격,물리,보조","Impale_Support"));
        dataList.put("마나흡수보조",new SupportGem("마나 흡수 보조 (31)","보조","Mana_Leech_Support"));
        dataList.put("치명타고통격화보조",new SupportGem("치명타 고통 격화 보조 (31)","치명타,보조","Critical_Strike_Affliction_Support"));
        dataList.put("고통격화보조",new SupportGem("고통 격화 보조 (31)","보조,지속시간","Swift_Affliction_Support"));
        dataList.put("새로운활력보조",new SupportGem("새로운 활력 보조 (31)","보조","Second_Wind_Support"));
        dataList.put("투사체속도감소보조",new SupportGem("투사체 속도 감소 보조 (31)","보조,투사체","Slower_Projectiles_Support"));
        dataList.put("향상된덫보조",new SupportGem("향상된 덫 보조 (31)","덫,보조","Advanced_Traps_Support"));
        dataList.put("연발사격보조",new SupportGem("연발 사격 보조 (38)","활,공격,보조,투사체","Barrage_Support"));
        dataList.put("치명타시시전보조",new SupportGem("치명타 시 시전 보조 (38)","치명타,보조,주문,발동","Cast_On_Critical_Strike_Support"));
        dataList.put("사망시시전보조",new SupportGem("사망 시 시전 보조 (38)","보조,주문,발동","Cast_on_Death_Support"));
        dataList.put("연쇄보조",new SupportGem("연쇄 보조 (38)","보조,연쇄의,투사체","Chain_Support"));
        dataList.put("위축의손길보조",new SupportGem("위축의 손길 보조 (38)","카오스,물리,공격,보조,지속시간","Withering_Touch_Support"));
        dataList.put("무리덫보조",new SupportGem("무리 덫 보조 (38)","덫,보조","Cluster_Traps_Support"));
        dataList.put("상위다중투사체보조",new SupportGem("상위 다중 투사체 보조 (38)","보조,투사체","Greater_Multiple_Projectiles_Support"));
        dataList.put("상위사격공세보조",new SupportGem("상위 사격 공세 보조 (38)","보조,투사체","Greater_Volley_Support"));
        dataList.put("명중시징표보조",new SupportGem("명중 시 징표 보조 (38)","보조,징표,발동","Mark_On_Hit_Support"));
        dataList.put("돌아오는투사체보조",new SupportGem("돌아오는 투사체 보조 (38)","보조,투사체","Returning_Projectiles_Support"));
        dataList.put("끔찍한독소보조",new SupportGem("끔찍한 독소 보조 (38)","보조","Vile_Toxins_Support"));
        dataList.put("각성한냉기피해추가보조",new SupportGem("각성한 냉기 피해 추가 보조 (72)","냉기,보조","Awakened_Added_Cold_Damage_Support"));
        dataList.put("각성한화살산개보조",new SupportGem("각성한 화살 산개 보조 (72)","활,공격,보조,투사체","Awakened_Arrow_Nova_Support"));
        dataList.put("각성한치명타시시전보조",new SupportGem("각성한 치명타 시 시전 보조 (72)","치명타,보조,주문,발동","Awakened_Cast_On_Critical_Strike_Support"));
        dataList.put("각성한연쇄보조",new SupportGem("각성한 연쇄 보조 (72)","보조,연쇄의,투사체","Awakened_Chain_Support"));
        dataList.put("각성한냉기관통보조",new SupportGem("각성한 냉기 관통 보조 (72)","냉기,보조","Awakened_Cold_Penetration_Support"));
        dataList.put("각성한치명적인상태이상보조",new SupportGem("각성한 치명적인 상태 이상 보조 (72)","보조","Awakened_Deadly_Ailments_Support"));
        dataList.put("각성한향상보조",new SupportGem("각성한 향상 보조 (72)","특출난,보조","Awakened_Enhance_Support"));
        dataList.put("각성한갈래보조",new SupportGem("각성한 갈래 보조 (72)","보조,투사체","Awakened_Fork_Support"));
        dataList.put("각성한상위다중투사체보조",new SupportGem("각성한 상위 다중 투사체 보조 (72)","보조,투사체","Awakened_Greater_Multiple_Projectiles_Support"));
        dataList.put("각성한고통격화보조",new SupportGem("각성한 고통 격화 보조 (72)","보조,지속시간","Awakened_Swift_Affliction_Support"));
        dataList.put("각성한포악한투사체보조",new SupportGem("각성한 포악한 투사체 보조 (72)","투사체,공격,물리,카오스,보조","Awakened_Vicious_Projectiles_Support"));
        dataList.put("각성한공허조작보조",new SupportGem("각성한 공허 조작 보조 (72)","카오스,보조","Awakened_Void_Manipulation_Support"));
        dataList.put("계몽보조",new SupportGem("계몽 보조 (1)","특출난,보조","Enlighten_Support"));
        dataList.put("비전쇄도보조",new SupportGem("비전 쇄도 보조 (1)","비전,보조,주문,지속시간","Arcane_Surge_Support"));
        dataList.put("원소확산보조",new SupportGem("원소 확산 보조 (1)","냉기,화염,번개,보조,효과범위","Elemental_Proliferation_Support"));
        dataList.put("분광격발보조",new SupportGem("분광 격발 보조 (1)","보조,주문,효과범위,화염,냉기,번개,분광,발동","Prismatic_Burst_Support"));
        dataList.put("연속주문보조",new SupportGem("연속 주문 보조 (4)","효과범위,주문,보조","Spell_Cascade_Support"));
        dataList.put("깊어지는집중유지보조",new SupportGem("깊어지는 집중 유지 보조 (4)","보조,집중 유지,지속시간","Infused_Channelling_Support"));
        dataList.put("환영소환보조",new SupportGem("환영 소환 보조 (4)","보조,소환수","Summon_Phantasm_Support"));
        dataList.put("번개피해추가보조",new SupportGem("번개 피해 추가 보조 (8)","번개,보조","Added_Lightning_Damage_Support"));
        dataList.put("연소보조",new SupportGem("연소 보조 (8)","화염,보조","Combustion_Support"));
        dataList.put("포식보조",new SupportGem("포식 보조 (8)","보조","Devour_Support"));
        dataList.put("효력보조",new SupportGem("효력 보조 (8)","보조,지속시간","Efficacy_Support"));
        dataList.put("치명타증가보조",new SupportGem("치명타 증가 보조 (8)","치명타,보조","Increased_Critical_Strikes_Support"));
        dataList.put("지옥불군단보조",new SupportGem("지옥불 군단 보조 (8)","화염,효과범위,보조,소환수","Infernal_Legion_Support"));
        dataList.put("소환수피해보조",new SupportGem("소환수 피해 보조 (8)","보조,소환수","Minion_Damage_Support"));
        dataList.put("연쇄폭발지뢰보조",new SupportGem("연쇄 폭발 지뢰 보조 (8)","보조,지뢰","Blastchain_Mine_Support"));
        dataList.put("벌어지는상처보조",new SupportGem("벌어지는 상처 보조 (8)","보조","Unbound_Ailments_Support"));
        dataList.put("효과집중보조",new SupportGem("효과 집중 보조 (18)","보조,효과범위","Concentrated_Effect_Support"));
        dataList.put("제어된파괴보조",new SupportGem("제어된 파괴 보조 (18)","주문,치명타,보조","Controlled_Destruction_Support"));
        dataList.put("포식자보조",new SupportGem("포식자 보조 (18)","보조,소환수,주문,지속시간","Predator_Support"));
        dataList.put("원소집중보조",new SupportGem("원소 집중 보조 (18)","보조","Elemental_Focus_Support"));
        dataList.put("시전속도증가보조",new SupportGem("시전 속도 증가 보조 (18)","보조,주문","Faster_Casting_Support"));
        dataList.put("신선한고기보조",new SupportGem("신선한 고기 보조 (18)","치명타,보조,소환수","Fresh_Meat_Support"));
        dataList.put("치명타피해증가보조",new SupportGem("치명타 피해 증가 보조 (18)","치명타,보조","Increased_Critical_Damage_Support"));
        dataList.put("소환수생명력보조",new SupportGem("소환수 생명력 보조 (18)","보조,소환수","Minion_Life_Support"));
        dataList.put("소환수속도보조",new SupportGem("소환수 속도 보조 (18)","이동,보조,소환수","Minion_Speed_Support"));
        dataList.put("과충전보조",new SupportGem("과충전 보조 (18)","번개,보조","Overcharge_Support"));
        dataList.put("물리번개전환보조",new SupportGem("물리 번개 전환 보조 (18)","번개,물리,보조","Physical_to_Lightning_Support"));
        dataList.put("치명타시권능충전보조",new SupportGem("치명타 시 권능 충전 보조 (18)","치명타,보조","Power_Charge_On_Critical_Support"));
        dataList.put("삼위일체보조",new SupportGem("삼위일체 보조 (18)","보조","Trinity_Support"));
        dataList.put("카오스피해추가보조",new SupportGem("카오스 피해 추가 보조 (31)","카오스,보조","Added_Chaos_Damage_Support"));
        dataList.put("대마법사보조",new SupportGem("대마법사 보조 (31)","번개,비전,보조,주문","Archmage_Support"));
        dataList.put("신성모독보조",new SupportGem("신성 모독 보조 (31)","보조,사술,오라","Blasphemy_Support"));
        dataList.put("충전된지뢰보조",new SupportGem("충전된 지뢰 보조 (31)","치명타,보조,지뢰","Charged_Mines_Support"));
        dataList.put("저주받은지대보조",new SupportGem("저주받은 지대 보조 (31)","효과범위,지속시간,보조,사술","Cursed_Ground_Support"));
        dataList.put("원소관통보조",new SupportGem("원소 관통 보조 (31)","보조","Elemental_Penetration_Support"));
        dataList.put("에너지흡수보조",new SupportGem("에너지 흡수 보조 (31)","보조","Energy_Leech_Support"));
        dataList.put("격분주입보조",new SupportGem("격분 주입 보조 (31)","보조,소환수,지속시간","Feeding_Frenzy_Support"));
        dataList.put("격화보조",new SupportGem("격화 보조 (31)","효과범위,주문,보조","Intensify_Support"));
        dataList.put("고충격지뢰보조",new SupportGem("고충격 지뢰 보조 (31)","지뢰,보조,효과범위,오라","High-Impact_Mine_Support"));
        dataList.put("임박한멸망보조",new SupportGem("임박한 멸망 보조 (31)","보조,사술,주문,효과범위,카오스,발동","Impending_Doom_Support"));
        dataList.put("아이템희귀도보조",new SupportGem("아이템 희귀도 보조 (31)","보조","Item_Rarity_Support"));
        dataList.put("번개관통보조",new SupportGem("번개 관통 보조 (31)","번개,보조","Lightning_Penetration_Support"));
        dataList.put("육탄방어보조",new SupportGem("육탄 방어 보조 (31)","보조,소환수","Meat_Shield_Support"));
        dataList.put("자극보조",new SupportGem("자극 보조 (31)","번개,보조,지속시간","Innervate_Support"));
        dataList.put("핵심조준보조",new SupportGem("핵심 조준 보조 (31)","보조,투사체,주문","Pinpoint_Support"));
        dataList.put("희생보조",new SupportGem("희생 보조 (31)","카오스,보조,주문","Sacrifice_Support"));
        dataList.put("원소의군단보조",new SupportGem("원소의 군단 보조 (31)","보조,소환수","Elemental_Army_Support"));
        dataList.put("재빠른낙인보조",new SupportGem("재빠른 낙인 보조 (31)","낙인,보조","Swiftbrand_Support"));
        dataList.put("사무치는한기보조",new SupportGem("사무치는 한기 보조 (38)","냉기,보조","Bonechill_Support"));
        dataList.put("기절시시전보조",new SupportGem("기절 시 시전 보조 (38)","보조,주문,발동","Cast_when_Stunned_Support"));
        dataList.put("집중유지중시전보조",new SupportGem("집중 유지 중 시전 보조 (38)","보조,집중 유지,주문,발동","Cast_while_Channelling_Support"));
        dataList.put("사술손길보조",new SupportGem("사술 손길 보조 (38)","보조,사술,발동","Hextouch_Support"));
        dataList.put("부패보조",new SupportGem("부패 보조 (38)","카오스,보조","Decay_Support"));
        dataList.put("차디찬유대보조",new SupportGem("차디찬 유대 보조 (38)","냉기,보조,연결,지속시간","Frigid_Bond_Support"));
        dataList.put("촉발보조",new SupportGem("촉발 보조 (38)","주문,보조","Unleash_Support"));
        dataList.put("사술의꽃보조",new SupportGem("사술의 꽃 보조 (38)","보조,사술","Hex_Bloom_Support"));
        dataList.put("점화확산보조",new SupportGem("점화 확산 보조 (38)","화염,보조,효과범위","Ignite_Proliferation_Support"));
        dataList.put("번제보조",new SupportGem("번제 보조 (38)","화염,보조","Immolate_Support"));
        dataList.put("효과범위증가보조",new SupportGem("효과범위 증가 보조 (38)","보조,효과범위","Increased_Area_of_Effect_Support"));
        dataList.put("지뢰밭보조",new SupportGem("지뢰밭 보조 (38)","보조,지뢰","Minefield_Support"));
        dataList.put("주문메아리보조",new SupportGem("주문 메아리 보조 (38)","주문,보조","Spell_Echo_Support"));
        dataList.put("주문칼날보조",new SupportGem("주문칼날 보조 (38)","보조,주문","Spellblade_Support"));
        dataList.put("각성한카오스피해추가보조",new SupportGem("각성한 카오스 피해 추가 보조 (72)","카오스,보조","Awakened_Added_Chaos_Damage_Support"));
        dataList.put("각성한번개피해추가보조",new SupportGem("각성한 번개 피해 추가 보조 (72)","번개,보조","Awakened_Added_Lightning_Damage_Support"));
        dataList.put("각성한신성모독보조",new SupportGem("각성한 신성 모독 보조 (72)","보조,사술,오라","Awakened_Blasphemy_Support"));
        dataList.put("각성한집중유지중시전보조",new SupportGem("각성한 집중 유지 중 시전 보조 (72)","보조,집중 유지,주문,발동","Awakened_Cast_While_Channelling_Support"));
        dataList.put("각성한제어된파괴보조",new SupportGem("각성한 제어된 파괴 보조 (72)","주문,치명타,보조","Awakened_Controlled_Destruction_Support"));
        dataList.put("각성한사술손길보조",new SupportGem("각성한 사술 손길 보조 (72)","보조,사술,발동","Awakened_Hextouch_Support"));
        dataList.put("각성한원소집중보조",new SupportGem("각성한 원소 집중 보조 (72)","보조","Awakened_Elemental_Focus_Support"));
        dataList.put("각성한계몽보조",new SupportGem("각성한 계몽 보조 (72)","특출난,보조","Awakened_Enlighten_Support"));
        dataList.put("각성한효과범위증가보조",new SupportGem("각성한 효과범위 증가 보조 (72)","보조,효과범위","Awakened_Increased_Area_of_Effect_Support"));
        dataList.put("각성한번개관통보조",new SupportGem("각성한 번개 관통 보조 (72)","번개,보조","Awakened_Lightning_Penetration_Support"));
        dataList.put("각성한소환수피해보조",new SupportGem("각성한 소환수 피해 보조 (72)","보조,소환수","Awakened_Minion_Damage_Support"));
        dataList.put("각성한연속주문보조",new SupportGem("각성한 연속 주문 보조 (72)","효과범위,주문,보조","Awakened_Spell_Cascade_Support"));
        dataList.put("각성한주문메아리보조",new SupportGem("각성한 주문 메아리 보조 (72)","주문,보조","Awakened_Spell_Echo_Support"));
        dataList.put("각성한벌어지는상처보조",new SupportGem("각성한 벌어지는 상처 보조 (72)","보조","Awakened_Unbound_Ailments_Support"));
        dataList.put("각성한촉발보조",new SupportGem("각성한 촉발 보조 (72)","주문,보조","Awakened_Unleash_Support"));

    }

    public Map<String, SupportGem> getDataList() {
        return dataList;
    }
}
